name: impak_retro
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/impaktek/impakdio

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  http_parser: ^4.1.2
  os_mime_type: ^0.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
