name: impak_retro
description: "ImpakRetro is a powerful Dart library for handling HTTP requests. Built on top of the [Dio](https://pub.dev/packages/dio) package, it offers a type-safe, configurable, and easy-to-use interface for interacting with APIs."
version: 1.1.1
homepage: https://github.com/impaktek/impak_retro

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  http_parser: ^4.1.2
  os_mime_type: ^0.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
